export const ADMIN_FETCH_LOADING = "ADMIN_FETCH_LOADING";
export const ADMIN_FETCH_MESSAGE = "ADMIN_FETCH_MESSAGE";
export const ADMIN_FETCH_ALL = "ADMIN_FETCH_ALL";
export const ADMIN_FETCH_SINGLE = "ADMIN_FETCH_SINGLE";
export const ADMIN_FETCH_ERROR = "ADMIN_FETCH_ERROR";