export const EVENT_FETCH_LOADING = "EVENT_FETCH_LOADING";
export const EVENT_FETCH_MESSAGE = "EVENT_FETCH_MESSAGE";
export const EVENT_FETCH_ALL = "EVENT_FETCH_ALL";
export const EVENT_FETCH_SINGLE = "EVENT_FETCH_SINGLE";
export const EVENT_FETCH_ERROR = "EVENT_FETCH_ERROR";